spring:
  application.name: exo33
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ps
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
management:
  endpoint:
    health:
      show-details: always